### ISSUE TITLE
Minimap: this plugin requires code-minimap installed!

### ISSUE THREAD

**Issue by BlueDruddigon** [wfxr/minimap.vim#123]
I am using LunarVim, an custom of neovim!

![image](https://user-images.githubusercontent.com/39997524/139241568-544f8044-69e2-4fb8-915f-9597075ba47e.png)

I've installed code-minimap via `cargo install --locked code-minimap` but it's still popup that message like i didnt install code-minimap!

Neovim Version: 5.0.1
My config for minimap.vim:

```
{
    'wfxr/minimap.vim',
    run = "cargo install --locked code-minimap",
    -- cmd = {"Minimap", "MinimapClose", "MinimapToggle", "MinimapRefresh", "MinimapUpdateHighlight"},
    config = function ()
      vim.cmd ("let g:minimap_width = 10")
      vim.cmd ("let g:minimap_auto_start = 1")
      vim.cmd ("let g:minimap_auto_start_win_enter = 1")
    end,
  },
```

I'm using Packer as Plugin Manager for nvim!

**Comment by jlgw** [comment]
I just faced this issue so I'll post my mistakes/caveats here in case anyone searches for the error message in the future.

You'll need to add `$HOME/.cargo/bin` to your  `$PATH` if you haven't done so already. If you make the mistake of adding `~/.cargo/bin` to `$PATH` you might expect it to work since you can call `:!code-minimap %` from vim, but since vim's `executable()` function doesn't do shell expansion it won't be found when the plugin is loaded and you'll get this error.

So, for it to work (provided you have already installed cargo)
1. Run `cargo install minimap`
2. Add the cargo bin directory to PATH, e.g. add `export PATH="$HOME/.cargo/bin:$PATH"` in your .bashrc (or .bash_profile etc)
3. Source the new shell rc or open a new terminal if you added the cargo bin to PATH in an rc file as per above. You should now be able to run `code-minimap --version`, `which code-minimap` should return the path and so on.
5. Run vim. It should now successfully load the plugin.

**Comment by jasperstam** [comment]
oh, you mean THIS 'cargo install minimap"???
```
 Compiling onig_sys v69.8.1
error: failed to run custom build command for `onig_sys v69.8.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installPnPDKY/release/build/onig_sys-bf9c0b8b0b0b99f2/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUSTONIG_DYNAMIC_LIBONIG
  cargo:rerun-if-env-changed=RUSTONIG_STATIC_LIBONIG
  cargo:rerun-if-env-changed=RUSTONIG_SYSTEM_LIBONIG

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.59.2/src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `minimap v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-installPnPDKY`
```
