### ISSUE TITLE
Code Lines in Minimap Shrink when Highlight Search is on (?)

### ISSUE THREAD

**Issue by ZN0N15** [wfxr/minimap.vim#127]
I'm honestly not sure if this was intended to happen, or if it is a bug, but the lines of code shown on the minimap do not match the code that is opened, because the lines are reduced or shrunk when turning on `g:minimap_highlight_search = 1`. The minimap without highlight-search correctly matches the lines/blocks of code in the opened file, but when turned on, it's like it shrinks or cut to the left.

Here's what I mean

![hlsearch](https://user-images.githubusercontent.com/57549197/146012364-5ed0261b-de60-45e2-856a-ed54da18ba97.png)

I would really want to keep the normal layout when highlight search is off, while keeping the highlight search feature turned on. Because it directly matches the layout of the code in the opened file/project. Is there any way to get this result? Or is this definitely just a bug?

**Comment by ZNielsen** [comment]
Oh interesting, actually the behavior on the left is the bugged behavior. 

### What's the difference?
The mm on the right is correctly scaled to fit the contents of the file horizontally without scrolling. This happens when there is a line that's long relative to the rest of the file (that line the the middle). If you were to go to the mm on the left and click into it, you should see that you can horizontally scroll on that long line in the middle. 

### Why only in search mode?
Here is the bug — We only calculate the buffer's max width if the search feature is enabled.

**Comment by ZN0N15** [comment]
Thank you! Will be looking forward to the update.

**Comment by ZN0N15** [comment]
While this issue is still open, I want to ask an different question before I open another issue. Is there any way to block or close the Minimap when on a different window layout? Like lets say I want the Minimap to close or not  open at all when I do a Vertical or Horizontal Split layout on neovim. I've been fiddling with the close/block buftypes/filetypes settings but I can't seem to get it to work. Is this currently not possible?

**Comment by ZNielsen** [comment]
Moving this to another issue so it's more searchable, I'll answer over there
