### ISSUE TITLE
Error when using Minimap in windows account with spaces in it

### ISSUE THREAD

**Issue by Chaoticsys101** [wfxr/minimap.vim#27]
I really like the idea of the plugin, it's that standard IDE feature in the command line, brilliant! But unfortunately when I tried it it didn't work. I am on a Windows machine and my username has spaces in it (it's 'Nuno David') (I don't recommend anyone to do so but unfortunately I did it). 
I got the following error when I did the ':Minimap' command:

minimap: could not generate minimap for C:\Users\Nuno David\\_vimrc
'C:\Users\Nuno' is not recognized as an internal or external command, ^@operable program or batch file.^@

The message seems straightforward, it doesn't allow spaces in the path and it gets cut right before the space.
I am planning to change my username soon (actually to create another account) so I guess everything will work fine then.
So do you think that this issue could be easily fixed? I doubt that many people will have this problem but I thought I would mention it. 

Thank you for your attention.

**Comment by rabirabirara** [comment]
@Chaoticsys101 I don't have an account with spaces in it, so I'd like your help: could you go into your plugin directory, into the minimap.vim directory, into the file autoload/minimap/vim.vim?  There is a series of lines near the top:

```vimscript
let s:bin_dir = expand('<sfile>:p:h:h:h').'/bin/'
if has('win32')
    let s:minimap_gen = s:bin_dir.'minimap_generator.bat'
else
    let s:minimap_gen = s:bin_dir.'minimap_generator.sh'
endif
let s:minimap_cache = {}
```

Could you surround the text `s:bin_dir.'minimap_generator.bat'` with the function name `fnameescape()`, and then test it to see if it works?  Thanks.

**Comment by rabirabirara** [comment]
To be specific, if `shellescape()` works as we expect, then this is very easily fixable.  I'm not capable of testing this without breaking my configuration entirely, so it falls on you to give us a hand.

This happens because this plugin needs to use a call to `system()` instead of `execute()` on Vim 8.2 (for some reason `execute()` is broken).  The `execute()` command allows the plugin to write the buffer to code-minimap; but with `system()`, we have to ask the shell to use code-minimap for us.  Because of this, we feed it the full path to the script `minimap_generator.bat` which typically has a path like `C:\Users\<username>\vimfiles\<plugin directory>\minimap.vim\bin\minimap_generator.bat`.  (In other words, Vim 8.2 is the problem here. 😛 )

Since your username has a space in it, the shell will misinterpret the command.  But if `shellescape()` does it's job and escapes characters according to your OS, then the fix is easy.

**Comment by Chaoticsys101** [comment]
Thank you for your prompt reply.
Unfortunately it didn't seem to work. Could the bug be inside the .bat itself? 
![minimap_test](https://user-images.githubusercontent.com/67800528/94666744-c339d880-0305-11eb-93d8-95d148c9a148.png)

**Comment by Chaoticsys101** [comment]
(answering your second reply)
Thanks for the explanation. 
This didn't seem to work either, however the error message is different. 
![minimap_shellescape](https://user-images.githubusercontent.com/67800528/94667982-6808e580-0307-11eb-935c-158b8bb9fb50.png)

**Comment by Chaoticsys101** [comment]
(answering your second reply)
Thanks for the explanation. 
This didn't seem to work either, however the error message is different. 
![minimap_shellescape](https://user-images.githubusercontent.com/67800528/94667982-6808e580-0307-11eb-935c-158b8bb9fb50.png)

**Comment by rabirabirara** [comment]
You are correct that the batch script is the problem.  I'd love it if Windows had a better shell (and if Powershell would work...), but for now I'll look into it myself.  Thanks.

**Comment by rabirabirara** [comment]
Actually, I believe I've made progress.  Could you return to the plugin directory, visit minimap.vim/bin/minimap_generator.bat, and change the line `set file=%4` to `set ""file=%4""`, and then see if it works?

**Comment by Chaoticsys101** [comment]
Yes I agree, Windows should have a better shell! 

Alright, thanks.

**Comment by Chaoticsys101** [comment]
Do you think it would be possible to use a relative path instead? Just like when we do ~/_vimrc, we don't need to say C:/Users/username/_vimrc.

**Comment by rabirabirara** [comment]
Yes, excuse that last comment; that was premature.  At any rate, I believe I've actually made progress this time.

```Batch
@ECHO OFF

:: Get argcount
set COUNT=0
for %%x in (%*) do set /A COUNT+=1

if %COUNT% NEQ 3 if %COUNT% NEQ 4  echo Usage: minimap_generator.bat ^<hscale^> ^<vscale^> ^<padding^> [file] & goto exit

set hscale=%1
set vscale=%2
set padding=%3
set "file=%4"


:: May not match test -z; PWSH is preferred
if %file% == "" goto nofile
:: else,
goto hasfile


:hasfile
:: Note: don't put quotes around "^%file^%" here.
code-minimap -H "%hscale%" -V "%vscale%" --padding "%padding%" %file%
goto exit


:nofile

code-minimap -H "%hscale%" -V "%vscale%" --padding "%padding%"
goto exit

:exit
```

Replace the contents of your batch file in minimap.vim/bin with the above code.  There are only three changes, but they have to do with strings and double quotes.  Specifically, they are to add quotes around `file=%4`, and to remove quotes around `%file%` wherever it comes up.  This seems to work on my computer.

**Comment by Chaoticsys101** [comment]
It works great!!
![IMG_20200930_220305](https://user-images.githubusercontent.com/67800528/94741860-b2707d80-036c-11eb-8627-6134049b4e9a.jpg)

Actually there are a few small issues.
- if I set the option that allows minimap to be on by default when starting vim it doesn't work properly. A cmd window pops up and it only goes back to normal if I close that window. 
![IMG_20200930_220725](https://user-images.githubusercontent.com/67800528/94742035-f794af80-036c-11eb-8f0b-dd731aa9e114.jpg)
- it also acts weird with the better whitespaces plugin (I actually disabled it because I don't think I really need it, but what happens if it's enabled is that the empty region on the minimap appears red even if there's no whitespace present) 
- this last one isn't an issue, just a simple question. It isn't supposed to work in cmd right? Because it seems to use braille characters, in cmd they appear as squares. 

Thank you for the help and the amazing plugin.

**Comment by rabirabirara** [comment]
Thanks for sticking around with me.  I'm not sure about the g:...auto_start breakage, and I can look into that when I finish some other bugs.  

As for CMD, it depends on your font.  You need to use a Unicode font that has Braille characters in it - I recommend using a Nerd font of some kind.  When I use my native CMD terminal with plain FiraCode, the minimap does show up as unrecognizable squares - however, when I change my terminal font to Cascadias mono, everything works.

![image](https://user-images.githubusercontent.com/59306451/94752461-28aabb00-0340-11eb-8f11-583265014f83.png)

As an aside, it was odd to debug your issue because Neovim and Vim interacted with the batch script differently.  If I replace the version of the script I sent you above for my Neovim plugin, then it will break (in general).  How strange!  We may have to keep two copies of the batch script; either that, or get a Powershell script working.  (Or, simply warn users about the matter in the FAQ, and direct them to this issue, to make the necessary changes themselves.)

**Comment by Chaoticsys101** [comment]
Thanks for the advice. I will be trying Nerd Font.
Oh really? I have never tried NeoVim

**Comment by Chaoticsys101** [comment]
This has nothing to do with the issue, sorry.
But you mentioned that I have to use a Unicode font. In my vimrc I have encoding set to utf-8, will that interfere?

**Comment by rabirabirara** [comment]
`utf-8` is a Unicode encoding, so it will definitely not interfere - that's what it's meant for!  I only mean that it needs to be a font that you know has Braille characters in it.

For example, if you visit the Github for Microsoft's Cascadia Code, they show a list of graphemes in the font.

![image](https://user-images.githubusercontent.com/59306451/94836436-d614e180-03c7-11eb-9ee1-aed5d335df72.png)

You can see the Braille among them.  Some fonts have these Braille characters; some don't, even though both fonts might be considered Unicode fonts.  (That, or some fonts just break when trying to display the Braille characters for some reason.)

UTF-8 is *the* most common encoding.  It is used literally everywhere, because software needs to be displayable everywhere.

The only reason you need to have `set encoding=utf-8` in your .vimrc is because Vim, by default, if it can't detect an encoding, uses `latin1` as default encoding.  But this is not what you want ever, unless you know that you need `latin1` over `utf-8`.

**Comment by Chaoticsys101** [comment]
Thanks for the explanation. I tried out some nerd fonts, it works in gvim but in cmd it doesn't detect braille characters, how weird. I haven't tried Microsoft's Cascadia yet

**Comment by rabirabirara** [comment]
It would probably depend on your terminal emulator.  Windows 10 has the Windows Terminal, which is what I use, and it works fantastic (frankly better than all the terminal emulators out there, Linux included).  Fonts in terminal UIs depend on the terminal settings; if gVim can display fonts properly, it's because it's a GUI application and has its own way of handling text.

If you were looking for reasons to upgrade, it would be a good idea to upgrade to Windows 10, to take full advantage of the developer tools available for it, since you're using Windows anyway.

At any rate, this issue is veering off topic; seeing as your specific issue was resolved, I'd ask that you close the issue (as *I* can't), unless you have other outstanding comments related to it.  If you have any further problems regarding an issue different to the one we've discussed here, please post a new issue; the other problems you've listed, for example, are separate of this one.  #29 is the PR which contains the proposed concrete fix to this issue.  If you want to continue discussion, you can always email me at my public email on my Github profile and I will happy to oblige.

**Comment by Chaoticsys101** [comment]
Thanks for your attention. 
You were of great help. Minimap now works great
