### ISSUE TITLE
Minimap closes on `:bd`, even if there are more buffers

### ISSUE THREAD

**Issue by ZNielsen** [wfxr/minimap.vim#94]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Question / Problem and steps to reproduce

I think minimap.vim decides whether or not to close based on the number of windows, but if we are just closing a buffer (not the whole window) the minimap should stay up if there are more buffers.

**Comment by ZNielsen** [comment]
It looks like this is due to a (IMO rather unintuitive) behavior of vim itself rather than anything the minimap is doing. Deleting a buffer closes windows for some reason. There are various plugins that manage that behavior a bit better, but I was able to get the behavior I was looking for with a simple mapping:
```vimscript
cnoremap bd b#<CR>:bd#<CR>
```

**Comment by ZNielsen** [comment]
A bit more complex, but more complete. This one opens a new buffer if there is no alternate file to switch to (rather than opening a buffer that I previously closed)
```vim
cnoremap bd<CR> call MyBufDelete()<CR>
function! MyBufDelete()
    if bufloaded('#')
        exec ':b#'
    else
        exec 'enew'
    endif
    exec ':bd#'
endfunction
```

**Comment by mikehaertl** [comment]
@ZNielsen I actually think this still is a valid bug. We should not need workarounds to make the minimap behave correctly when a buffer is closed with `:bd`. It's a very common command.

The issue for me is that if I have multiple buffers opened, the map goes away if I close a buffer with `:bd`. It comes back if I switch to another buffer.

I've fixed it for now with:

```viml
autocmd BufEnter * Minimap
```

I wonder if that shouldn't be the default anyway instead of `BufWinEnter`:
https://github.com/wfxr/minimap.vim/blob/45a8eabefd500ab4496ee790d3ac178eb4de9fb9/plugin/minimap.vim#L133-L141

**Comment by ZNielsen** [comment]
If you think this improves behavior we would love a PR! IMO you should break down the difference so reviewers don't have to go to the docs to understand what the PR would do.
